a = input('Digite ago: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaço?', a.isspace())
#print('É um número? ', texto.isnumeric())
print('É alfabético? ', a.isalpha())
print('é Alfanúmero? ', a.isalnum())
print('Está em minusculo? ', a.islower())
print('Está em maiscula? ', a.isupper())
print('Está capitalizada? ', a.istitle())
print('É um número ? {} '.format(a.isnumeric()))
